### ISSUE TITLE
Incorrect setting of tree_threshold in largeVis()

### ISSUE THREAD

**Issue by yixuan** [elbamos/largeVis#37]
According to the [documentation](https://github.com/elbamos/largeVis/blob/master/R/largeVis.R#L8), `tree_threshold` by default is the number of features of the input matrix. However, the [code](https://github.com/elbamos/largeVis/blob/master/R/largeVis.R#L63) shows that it is actually set to be the number of observations.

**Comment by elbamos** [comment]
Its correct - remember that the package wants the input matrix to be transposed from the R standard, so that observations are columns and features are rows. 

(The reason for this is memory -- the C++ libraries need data in column-ordered format to be efficient, and transposing would double the size needed for the dataset.  Issues like this begin to matter when the data size gets very large, which is the point of the package.)

**Comment by yixuan** [comment]
Yeah, that's what I find confusing. Given the matrix layout, `nrow(x)` equals the number of features, and `ncol(x)` equals the number of observations. It seems we need `nrow(x)` here.

**Comment by elbamos** [comment]
Hey you're right, thanks!  I had this correct in randomProjectionTreeSearch but not largeVis.  I've changed it now, but if you want to submit a PR with the change so you get the commit, I'll accept the PR.

**Comment by yixuan** [comment]
This is just a quick fix, so I would close this issue and let you fix it later. 😄
