### ISSUE TITLE
LargeVis vs tSNE clustering

### ISSUE THREAD

**Issue by akhst7** [elbamos/largeVis#56]
I have this data frame of 20,000 options with 14 distinct parameters.  A standard Rtsne generates relatively well distributed and balanced clusters as follows;
![rplot](https://user-images.githubusercontent.com/3075799/39847216-637ffe26-53ce-11e8-9beb-336ff518845b.png)

However, I have been struggling to generate the similar plot.  I've been playing with K and n_tree but have not quite get the plot that comes close to tSNE's.  

e.g. `v<-largeVis(test, K=200, n_tree=200, distance_method = "Eucledian", threads = 16)`

![rplot01](https://user-images.githubusercontent.com/3075799/39847425-8936fc04-53cf-11e8-98ae-d1b63259b90f.png)

I'd appreciate if you could give me some pointer to start (stackoerflow was not helpful).

**Comment by elbamos** [comment]
That looks to me like a plot of an hdbscan clustering, possibly over a largevis dimensionality reduction.

If so, I’m not sure what the objection is to the largevis plot. Is it that there’s a bunch of biggish clusters rather than a larger number of smaller ones? If so you could try reducing K. You might also consider scaling the data.

If you were looking for a particular result, you might add dimensionality to help you get there, effectively semi-supervising.

But in general, it’s important to remember that neither tsne nor largevis guarantees an outcome that’s either aesthetically pleasing or produces whatever separation was desired a priori.
